#!/bin/sh /etc/rc.common

# OpenWRT nooLite init script

START=70

start() {
    echo start
    service_start /usr/bin/nooliterx -d
    service_start /usr/bin/noolitepcd -d
}

stop() {
    echo stop
    service_stop /usr/bin/nooliterx
    service_stop /usr/bin/noolitepcd
}

